### ISSUE TITLE
can't run docker pull jahaniam/orbslam3, permission denised

### ISSUE THREAD

**Issue by catproof** [jahaniam/orbslam3_docker#1]
**when I run:**
docker pull jahaniam/orbslam3

**I get the following output:**
Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=jahaniam%2Forbslam3&tag=latest": dial unix /var/run/docker.sock: connect: permission denied

**Comment by jahaniam** [comment]
Did you properly finish docker installation? Is your user added to the docker group?
https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket
what is your output when you do `docker ps -a` ?

Try `sudo docker pull  jahaniam/orbslam3` if this works, you will need to add usergroup docker and add your user to that usergroup and restart your machine to fix it.

The dockerhub image `jahaniam/orbslam3` itself is public and you should have access to pull it.

**Comment by catproof** [comment]
ok, I resolved that issue, I didn't think it was just a simple permission fix on my side! thank you for the help. I am running into a new problem... see my output:


nicolas@nicolas-ROG-Strix-G731GT-G731GT:~/orbslam3_docker$ sudo ./build_container.sh 
xauth:  timeout in locking authority file /run/user/1000/gdm/Xauthority
xauth: (argv):1:  unable to read any entries from file "(stdin)"
non-network local connections being added to access control list
Error: No such container: orbslam3
2aec97783b9018789a679abea05367e2c53e57c69f9bdc0e2b964bfb18c0abad
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
Error response from daemon: Container 2aec97783b9018789a679abea05367e2c53e57c69f9bdc0e2b964bfb18c0abad is not running
Error response from daemon: Container 2aec97783b9018789a679abea05367e2c53e57c69f9bdc0e2b964bfb18c0abad is not running


Just to make sure the image download properly, I did the following:
nicolas@nicolas-ROG-Strix-G731GT-G731GT:~/orbslam3_docker$ docker image list
REPOSITORY          TAG       IMAGE ID       CREATED        SIZE
hello-world         latest    feb5d9fea6a5   16 hours ago   13.3kB
jahaniam/orbslam3   latest    f2c152cf350a   12 days ago    2.63GB


any ideas on what is going on?

**Comment by jahaniam** [comment]
There are two issues here. 
xauth: (argv):1: unable to read any entries from file "(stdin)" which I am not sure of it

I should have mentioned this is the nvidia driver image. You should have nvidia-docker set up. The docker takes advantage of the gpu if someone wants to run a deep learning model to increase the accuracy of the orbslam3 it is suitable.

I am working on a cpu based that works with Xorg. I tested it and will update the instructions in an hour or so.

Meanwhile can you confirm what is the display driver you are running? got to `additional drivers` section and see if it is Xorg or Nvidia? And do you have nvidia graphic card?

**Comment by jahaniam** [comment]
I have added the cpu version and updated the documentation. Please try that out. It should work if you don't have nvidia drivers running.

**Comment by catproof** [comment]
I'm not sure how to 'go to additional drivers', but i can confirm my machine has an nvidia card. I started building the cpu container, it looks like it is working now. I will set up my nvidia docker later. thanks so much for the help by the way :)

**Comment by jahaniam** [comment]
That’s good to hear. If the cpu version worked for you and you have nvidia card, I can tell you are running on xorg and you don’t have nvidia drivers installed. I suggest you to get best out of your gpu install your nvidia drivers.

In terminal run `software-properties-gtk --open-tab=4` to get into additional drivers and you’ll see what display drivers you are running.

I will close this issue then.

**Comment by catproof** [comment]
> There are two issues here. xauth: (argv):1: unable to read any entries from file "(stdin)" which I am not sure of it
> 
> I should have mentioned this is the nvidia driver image. You should have nvidia-docker set up. The docker takes advantage of the gpu if someone wants to run a deep learning model to increase the accuracy of the orbslam3 it is suitable.
> 
> I am working on a cpu based that works with Xorg. I tested it and will update the instructions in an hour or so.
> 
> Meanwhile can you confirm what is the display driver you are running? got to `additional drivers` section and see if it is Xorg or Nvidia? And do you have nvidia graphic card?

Hi there,

You mentioned some people might want to use deep learning to enhance Orb Slam. I thought of this as well. Do you know of anyone, any github repos, or research papers that use deep learning to enhance an existing SLAM solution? I'd like to investigate this more.
