### ISSUE TITLE
Failed to open Xdisplay

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [jahaniam/orbslam3_docker#15]
I am trying to test orbslam with EuRoC dataset but when I run euroc_examples.sh I am getting the error below; 

```
terminate called after throwing an instance of 'std::runtime_error'
what():  Pangolin X11: Failed to open X display
Aborted (core dumped)
```
I have tried `xhost +local:docker` but nothing happened. Can you help me with this ?

**Comment by jahaniam** [comment]
Make sure the `echo $DISPLAY` in your host and container are same. 
If you are using nvidia, make sure your nvidia driver is running by running `nvidia-smi`
