### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by satyapalsinh10** [jahaniam/orbslam3_docker#20]
I am trying to run the ORB_SLAM3 using dockers and when I run the below step

`
cd /ORB_SLAM3/Examples&&./euroc_examples.sh
`

It gives me an error of:

root@ashiq-asus:/ORB_SLAM3# cd /ORB_SLAM3/Examples&&./euroc_examples.sh
bash: ./euroc_examples.sh: No such file or directory

Can you please help?

**Comment by jahaniam** [comment]
Thanks for pointing it out. The eurouc examples were removed in orbslam3 1.0 .  I’ve added it back in my branch and update the code. Feel free to retry. It should work

**Comment by rakshitx1** [comment]
Still getting same issue, I tried the main branch.

`download_dataset_sample.sh` works perfectly, I am able to download samples to my host machine, but the `/ORB_SLAM3` is an empty directory in the docker container
