### ISSUE TITLE
DIsplay

### ISSUE THREAD

**Issue by AyonRRahman** [jahaniam/orbslam3_docker#21]
Hello. I was trying to run the orbslam3 in docker as mentioned. But I am not getting any display. It is running and saving the trajectory but without any display

**Comment by jahaniam** [comment]
Do you tun on cuda?

**Comment by AyonRRahman** [comment]
I could fix it by changing the code of initialization of the orbslam examples. Apparently it was turned off in recent version of orbslam.

**Comment by zhk779** [comment]
> I could fix it by changing the code of initialization of the orbslam examples. Apparently it was turned off in recent version of orbslam.

Hello, I have encountered the same problem, can you tell me which part of the code needs to be modified?

**Comment by Lucbus** [comment]
It is a little late now, but for all the others who have the same question: You have to change the boolean in the following line:
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/4452a3c4ab75b1cde34e5505a36ec3f9edcdc4c4/Examples/Monocular/mono_euroc.cc#L83
