### ISSUE TITLE
Incorrect ROS Sourcing in Dockerfile

### ISSUE THREAD

**Issue by rakshitx1** [jahaniam/orbslam3_docker#23]
**Issue Description:**

The Dockerfile.cuda provided in the repository installs ROS Noetic, but incorrectly sources the ROS Melodic setup script in the user's `.bashrc` file. This inconsistency may lead to errors and unexpected behavior when attempting to use ROS within the Docker container.

**Steps to Reproduce:**

1. Clone the repository.
2. Build the Docker image using the provided Dockerfile.cuda.
3. Start the Docker container.
4. Source the `.bashrc` file and attempt to use ROS commands.

**Expected Behavior:**

The Dockerfile should correctly source the ROS Noetic setup script in the user's `.bashrc` file to ensure consistency with the installed ROS version.

**Actual Behavior:**

The Dockerfile.cuda incorrectly sources the ROS Melodic setup script in the user's `.bashrc` file, leading to potential conflicts and errors when using ROS commands.

**Proposed Solution:**

Update the Dockerfile to source the ROS Noetic setup script in the user's `.bashrc` file.

**Comment by jahaniam** [comment]
Right, I forgot to update that! Thanks for notifying me! I will fix and test it in the next 3 days! Feel free to provide a PR for the credit as well if you want.

**Comment by jahaniam** [comment]
I also add more fixes and updated the image on dockerhub. We should be good now. Thanks for the PR.
