### ISSUE TITLE
Running ROS nodes

### ISSUE THREAD

**Issue by migsdigs** [jahaniam/orbslam3_docker#29]
Hi there,

It looks as though the ROS examples are no longer available in /Examples/ROS, but have been moved to /Examples_old/ROS. As a result the build fails as it is not able to locate the directory. Furthermore, the ROS_PACKAGE_PATH should be changed to account for this.

Thanks

**Comment by migsdigs** [comment]
The problem appears to be that [build_container_cuda.sh](https://github.com/jahaniam/orbslam3_docker/blob/main/build_container_cuda.sh) (and build_container_cpu.sh) pull the latest release version of the original [ORB_SLAM3](https://github.com/UZ-SLAMLab/ORB_SLAM3) repo. It should be pulling one of the earlier beta tags that the ROS examples were written for (you will notice that ROS examples are now located in `/Examples_old`). I used the [v0.4-beta](https://github.com/UZ-SLAMLab/ORB_SLAM3/tree/v0.4-beta) version of the repo, and change lines 47-49 of `build_container_cuda.sh` from:
```
# Git pull orbslam and compile
docker exec -it orbslam3 bash -i -c  "git clone -b add_euroc_example.sh https://github.com/jahaniam/ORB_SLAM3.git /ORB_SLAM3 && cd /ORB_SLAM3 && chmod +x build.sh && ./build.sh "
# Compile ORBSLAM3-ROS
docker exec -it orbslam3 bash -i -c "echo 'ROS_PACKAGE_PATH=/opt/ros/noetic/share:/ORB_SLAM3/Examples/ROS'>>~/.bashrc && source ~/.bashrc && cd /ORB_SLAM3 && chmod +x build_ros.sh && ./build_ros.sh"
```

to 

```
# Git pull orbslam and compile
docker exec -it orbslam3 bash -i -c  "git clone -b v0.4-beta https://github.com/UZ-SLAMLab/ORB_SLAM3.git /ORB_SLAM3 && cd /ORB_SLAM3 && chmod +x build.sh && ./build.sh "
# Compile ORBSLAM3-ROS
docker exec -it orbslam3 bash -i -c "echo 'ROS_PACKAGE_PATH=/opt/ros/noetic/share:/ORB_SLAM3/Examples/ROS'>>~/.bashrc && source ~/.bashrc && cd /ORB_SLAM3"
```

**Note:** It is important not to build the ROS packages yet

I then started the container as per usual with `docker exec -it orbslam3 bash`.

Both Python 2 and Python 3.8 are installed inside of the container, but it is important that Python 3 is seen as default for the build, so you can do:
```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
sudo update-alternatives --config python
python --version
```
The last line should confirm that Python 3 is now seen as default.

Check OpenCV version `opencv_version`, it should output 4.4.0. 

Open [CMakeLists.txt ](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/v0.4-beta/CMakeLists.txt) and alter lines 36-42 to the following (I do not think this is strictly necessary but I did it just in case):
```
find_package(OpenCV 4.4)
if(NOT OpenCV_FOUND)
  find_package(OpenCV 4.0)
  if(NOT OpenCV_FOUND)
    message(FATAL_ERROR "OpenCV > 4.0 not found.")
  endif()
endif()
```

Open [/Examples/ROS/ORB_SLAM3/CMakeLists.txt](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/v0.4-beta/Examples/ROS/ORB_SLAM3/CMakeLists.txt) and add `project(ORB_SLAM3)` below  `cmake_minimum_required(VERSION 2.4.6)`.

Also changes lines 33-42 to:
```
find_package(OpenCV 4.4 QUIET)
if(NOT OpenCV_FOUND)
   find_package(OpenCV 3.0 QUIET)
   if(NOT OpenCV_FOUND)
      message(FATAL_ERROR "OpenCV > 3.0 not found.")
   endif()
endif()

find_package(Eigen3 3.1.0 REQUIRED)
find_package(Pangolin REQUIRED)
```

Finally, build the ROS package with `build_ros.sh` inside of /ORB_SLAM3 (make sure it is executable first). You should now be able to run the ROS nodes as per the examples in the original [ORB_SLAM3](https://github.com/UZ-SLAMLab/ORB_SLAM3/tree/v0.4-beta) repo.

**Comment by migsdigs** [comment]
#26 This should help you as well

**Comment by jahaniam** [comment]
@migsdigs  can you please provide a PR with your fixes? 

Unfortunately I dont have enough time to fully maintain this repo.  Thanks a lot.

**Comment by migsdigs** [comment]
> @migsdigs can you please provide a PR with your fixes?
> 
> Unfortunately I dont have enough time to fully maintain this repo. Thanks a lot.

Hi @jahaniam, I would love to provide PR, but it is actually a bit complicated since some of the changes I have had to make are in the ORB_SLAM3 repo, which you are pulling in your dockerfile. I have also managed to get ROS to run on the latest release version of the ORB repo by following the same steps I listed above and some other changes. I suppose for this to really be effective I would have to get a PR on the original ORB_SLAM3 repo before I do a PR on yours? Maybe you can help me help you?

Thanks mate

**Comment by jahaniam** [comment]
I have a fork of ORBSLAM3. Initially, there were other issues related to opencv new version I had to do on my fork and when it got fixed upstream I pointed back to original orbslam3 repo. If you can get a PR on that fork, we can point it to the ORBSLAM3 to fix the issue. It better allow me to review the changes that is needed to fix this.

https://github.com/jahaniam/ORB_SLAM3
