### ISSUE TITLE
bash: cd: ORB_SLAM3: No such file or directory

### ISSUE THREAD

**Issue by catproof** [jahaniam/orbslam3_docker#4]
When I ran 'sudo ./build_container_cuda.sh' I somehow got this error:

[ 90%] Linking CXX executable ../Examples/Stereo/stereo_kitti
[ 91%] Linking CXX executable ../Examples/Monocular/mono_kitti
[ 92%] Linking CXX executable ../Examples/Monocular/mono_tum_vi
[ 93%] Linking CXX executable ../Examples/Stereo/stereo_euroc
[ 95%] Linking CXX executable ../Examples/Stereo/stereo_tum_vi
[ 96%] Linking CXX executable ../Examples/Monocular-Inertial/mono_inertial_tum_vi
[ 97%] Linking CXX executable ../Examples/Monocular-Inertial/mono_inertial_euroc
[ 97%] Built target stereo_kitti
[ 97%] Built target rgbd_tum
[ 97%] Built target mono_kitti
[ 97%] Built target mono_euroc
[ 97%] Built target mono_tum
[ 97%] Built target mono_tum_vi
[ 97%] Built target stereo_euroc
[ 97%] Built target stereo_tum_vi
[ 97%] Built target mono_inertial_tum_vi
[ 98%] Linking CXX executable ../Examples/Stereo-Inertial/stereo_inertial_tum_vi
[ 98%] Built target mono_inertial_euroc
[100%] Linking CXX executable ../Examples/Stereo-Inertial/stereo_inertial_euroc
[100%] Built target stereo_inertial_tum_vi
[100%] Built target stereo_inertial_euroc
bash: cd: ORB_SLAM3: No such file or directory

even though when I type in ls, it shows that the ORB_SLAM3 directory exists:
nicolas@nicolas-ROG-Strix-G731GT-G731GT:~/orbslam3_docker$ ls
build_container_cpu.sh  build_container_cuda.sh  build_image.sh  Datasets  Dockerfile  Dockerfile_cpu  download_dataset_sample.sh  ORB_SLAM3  README.md  ros_entrypoint.sh

I imagine your script is failing at line 48, because it looks like Orb Slam compiled correctly. My computer went into sleep mode while I was running your bash script, I wonder if this has anything to do with it... Very strange error!

**Comment by catproof** [comment]
I will try typing in the commands manually, and see if it can run that way.

**Comment by jahaniam** [comment]
Thanks for noticing this. I recently changed the workdir of the docker image. line 48 should be:

```
docker exec -it orbslam3 bash -i -c "echo 'ROS_PACKAGE_PATH=/opt/ros/melodic/share:/ORB_SLAM3/Examples/ROS'>>~/.bashrc && source ~/.bashrc && cd /ORB_SLAM3 && chmod +x build_ros.sh && ./build_ros.sh"
```

I forgot to edit ORB_SLAM3 to /ORB_SLAM3

**Comment by jahaniam** [comment]
Please do a `git pull` and retry. it should be fixed.
