### ISSUE TITLE
Trouble compiling on macOS [Noob]

### ISSUE THREAD

**Issue by boahemaa** [jahaniam/orbslam3_docker#7]
Hi, total Docker and macOS (work reasons) beginner here. I’m trying to get the container running on macOS [cpu].
I’m aware that the GUI most likely won’t work as hinted in #3. For the start I just want to get the package compiled.
When running build_container_cpu.sh I run into many deprecation warnings from Eigen like the following one:

In file included from /ORB_SLAM3/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:38:0,
                 from /ORB_SLAM3/include/Converter.h:26,
                 from /ORB_SLAM3/src/Converter.cc:19:
/ORB_SLAM3/Thirdparty/g2o/g2o/types/../core/base_binary_edge.h: In instantiation of ‘class g2o::BaseBinaryEdge<6, g2o::SE3Quat, g2o::VertexSE3Expmap, g2o::VertexSE3Expmap>’:
/ORB_SLAM3/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:83:24:   required from here
/ORB_SLAM3/Thirdparty/g2o/g2o/types/../core/base_binary_edge.h:59:80: warning: ‘Eigen::AlignedBit’ is deprecated [-Wdeprecated-declarations]
       typedef Eigen::Map<Matrix<double, Di, Dj>, Matrix<double, Di, Dj>::Flags & AlignedBit ? Aligned : Unaligned > HessianBlockType;

and then after some time I get this error: 

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/ORB_SLAM3.dir/build.make:88: recipe for target 'CMakeFiles/ORB_SLAM3.dir/src/LocalMapping.cc.o' failed
make[2]: *** [CMakeFiles/ORB_SLAM3.dir/src/LocalMapping.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....

This error lead me to raulmur/ORB_SLAM2#661 which makes me believe that I maybe have to downgrade the Eigen version, perhaps in Dockerfile_cpu? However, I could not figure out how to do that. 

Following this error are multiple unused variables warnings like the following:

/ORB_SLAM3/src/Optimizer.cc:6921:10: warning: unused variable ‘bOut’ [-Wunused-variable]
     bool bOut = false;
          ^~~~
/ORB_SLAM3/src/Optimizer.cc: In static member function ‘static void ORB_SLAM3::Optimizer::OptimizeEssentialGraph4DoF(ORB_SLAM3::Map*, ORB_SLAM3::KeyFrame*, ORB_SLAM3::KeyFrame*, const KeyFrameAndPose&, const KeyFrameAndPose&, const std::map<ORB_SLAM3::KeyFrame*, std::set<ORB_SLAM3::KeyFrame*> >&)’:

Am I on the right track with modifying the Dockerfile_cpu installs? Is trying to get the image running on macOS a lost cause anyways?

Thank you very much for your help and for providing this package!

**Comment by boahemaa** [comment]
I switched over to match08's macOS implementation which works nicely for me.

**Comment by ravilakhotia2006** [comment]
@boahemaa - Could you share steps ? I tried with match08's macOS implementation. Still seeing these errors.
